version: '3.8'

services:
  db:
    image: postgis/postgis
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    env_file:
      - ../.env
    depends_on:
      - db
    command: ["python", "pipeline/etl.py"]

volumes:
  pgdata:
